/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8e3504d2-92bc-4aef-b566-e312b93bcb01",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SG52NvVZB",
    "aws_user_pools_web_client_id": "713uo2185ihbtfn1abj64p8dae",
    "oauth": {}
};


export default awsmobile;
